from SistemaVentas.models.usuario import Usuario
from SistemaVentas.models.producto import Producto
from SistemaVentas.models.precio import Precio
from SistemaVentas.models.factura import Factura
from SistemaVentas.models.venta_producto import VentaProducto
from SistemaVentas.models.movimiento import *
from SistemaVentas.models.turno import Turno
from SistemaVentas.models.compra_inventario import CompraInventario
from SistemaVentas.models.deuda import Deuda
